"""Generate the static dashboard demo that Vercel serves.

WHY THIS EXISTS, AND WHAT IT IS NOT. ZEUS itself cannot be deployed: it is a
macOS daemon that holds a microphone open, runs under launchd, shells out to
`say`, and writes SQLite on your disk. Vercel runs ephemeral serverless
functions with no persistent process, no audio device and no macOS.

Nor should the REAL dashboard ever be deployed. It shows every goal, every
transcript and every tool call with no authentication, which is only safe
because it binds 127.0.0.1 and is unreachable from anywhere else. Publishing
it would invert the whole security model.

So this builds a frozen page from INVENTED data, to show the project. It is
generated from the real renderer, so the demo cannot drift from the product;
it is regenerated by running this script, not by hand-editing the output.

    python tools/build_demo.py demo/index.html
"""
from __future__ import annotations

import re
import sys
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from zeus.clock import FakeClock                                    # noqa: E402
from zeus.dashboard.data import read_snapshot                       # noqa: E402
from zeus.dashboard.render import render_page                       # noqa: E402
from zeus.memory.journal import Journal                             # noqa: E402
from zeus.memory.store import Store                                 # noqa: E402

TZ = ZoneInfo("America/Los_Angeles")
NOW = datetime(2026, 8, 7, 14, 20, tzinfo=TZ).astimezone(timezone.utc)

GOALS = [
    ("2026-08-07", "Finish the dashboard and merge it", "pending", None),
    ("2026-08-06", "Fix the stale-retry data loss", "done", "Took most of the morning."),
    ("2026-08-05", "Wire the retry ladder", "done", "Done before lunch."),
    ("2026-08-04", "Write the end-to-end test", "done", None),
    ("2026-08-03", "Rest day", "missed", "Went hiking instead. No regrets."),
    ("2026-08-02", "Draft the spec", "done", None),
    ("2026-08-01", "Sketch the architecture", "done", None),
    ("2026-07-31", "Read the openWakeWord docs", "partial", "Got halfway."),
    ("2026-07-30", "Set up the repo", "done", None),
]

BANNER = """
<div class="banner" style="color:var(--info);background:var(--info-bg);
     border-color:var(--info)">
  <b>Demo — every goal, transcript and tool call below is invented.</b>
  This is the page <code>zeus dashboard</code> renders, frozen to a static
  file. The real one binds <code>127.0.0.1</code> and never leaves your Mac;
  it is not deployable, and deliberately so.
  <a href="https://github.com/" style="color:var(--info);text-decoration:underline">
  Source on GitHub</a>
</div>"""


def build(root: Path) -> str:
    clock = FakeClock(NOW)
    store = Store(root / "zeus.db", clock)
    journal = Journal(root / "journal", clock, TZ)

    for date, text, status, notes in GOALS:
        goal_id = store.set_goal(date, text)
        if status != "pending":
            store.update_goal(goal_id, status, notes)

    for day in ("2026-08-07", "2026-08-06"):
        parsed = datetime.strptime(day, "%Y-%m-%d")
        at = lambda h: datetime(parsed.year, parsed.month, parsed.day, h, 0, tzinfo=TZ)
        morning = store.open_checkin("morning", at(11), day)
        store.update_checkin(morning, outcome="answered", attempts=1, fired_at=at(11))
        evening = store.open_checkin("evening", at(21), day)
        if day == "2026-08-06":
            store.update_checkin(evening, outcome="answered", attempts=1,
                                 fired_at=at(21))
        else:
            store.update_checkin(evening, outcome="deferred", attempts=2,
                                 retry_at=NOW + timedelta(minutes=14))

    morning_chat = store.start_conversation("schedule")
    store.add_message(morning_chat, "assistant", "Morning. What's the one thing today?")
    store.add_message(morning_chat, "user", "Finish the dashboard and merge it.")
    store.add_message(morning_chat, "assistant",
                      "Got it — finish the dashboard and merge it. Saved.")
    store.log_action("save_goal", {"text": "Finish the dashboard and merge it"},
                     "Saved today's goal", True, 9, conversation_id=morning_chat)
    store.end_conversation(morning_chat)

    review = store.start_conversation("schedule")
    store.add_message(review, "assistant",
                      "How did it go with fixing the stale-retry bug?")
    store.add_message(review, "user", "Done. Took most of the morning.")
    store.log_action("record_outcome",
                     {"status": "done", "notes": "Took most of the morning."},
                     "Recorded: done", True, 11, conversation_id=review)
    store.log_action("record_outcome", {"status": "done"}, None, False, 6,
                     error="There is no goal recorded for today.",
                     conversation_id=review)
    store.end_conversation(review)

    # Left OPEN on purpose: an open row is what raises the wake-word pop-up,
    # which is the thing a demo most needs to show.
    live = store.start_conversation("wake")
    store.add_message(live, "user", "What did I say I'd do today?")
    store.add_message(live, "assistant", "Finish the dashboard and merge it.")

    store.upsert_job("checkin_morning", "0 11 * * *")
    store.upsert_job("checkin_evening", "0 21 * * *")
    store.set_job_run("checkin_morning", NOW - timedelta(hours=3))
    store.set_heartbeat()
    journal.append("Goal set: Finish the dashboard and merge it")
    journal.append("Wake conversation: 2 messages")
    store.close()

    settings = {
        "timezone": "America/Los_Angeles", "morning": "11:00", "evening": "21:00",
        "model": "claude-opus-5", "wake word": "hey_jarvis",
        "speech-to-text": "local_whisper (base.en)",
        "text-to-speech": "mac_say (Alex)", "data directory": "~/.zeus",
    }
    page = render_page(
        read_snapshot(root / "zeus.db", root / "journal", TZ, NOW, settings)
    )

    # The poller is removed rather than left to fail: there is no /api/session
    # behind a static file, so it would retry every two seconds forever and
    # fill the console with errors. The pop-up is server-rendered anyway, so
    # the demo still shows it -- just frozen, which is honest for a demo.
    page = re.sub(r"<script>.*?</script>", "", page, flags=re.S)
    return page.replace('<main class="content">', f'<main class="content">{BANNER}')


def main() -> int:
    out = Path(sys.argv[1] if len(sys.argv) > 1 else "demo/index.html")
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        page = build(Path(tmp))
    out.write_text(page, encoding="utf-8")
    assert "<script" not in page, "the static demo must carry no script"
    print(f"wrote {out} ({len(page):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
